spring.application.name=api-gateway

server.port=8090

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

spring.cloud.gateway.mvc.routes[0].id=clientes-route
spring.cloud.gateway.mvc.routes[0].uri=lb://ms-clientes
spring.cloud.gateway.mvc.routes[0].predicates[0]=Path=/clientes/**

spring.cloud.gateway.mvc.routes[1].id=pedidos-route
spring.cloud.gateway.mvc.routes[1].uri=lb://ms-pedidos
spring.cloud.gateway.mvc.routes[1].predicates[0]=Path=/pedidos/**